[package]
    name = "control-blocks"
    version = "0.1.0"
    entrypoint = "control-blocks.typ"
    authors = ["ivaquero"]
    license = "MIT"
    description = "Draws control blocks using fletcher and CeTZ"
    repository = "https://github.com/ivaquero/typst-control-blocks"
